name: Build Main Frontend

on:
  push:
    paths: "brainPop/Frontend"
  workflow_dispatch:
jobs:
  build:
    defaults:
      run:
        working-directory: brainPop/Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "22"
      - name: Install Packages
        run: npm ci --force
      - name: Build
        run: npm run build
